### ISSUE TITLE
Plot 3D with normals

### ISSUE THREAD

**Issue by pvjosue** [PolarizedLightFieldMicroscopy/forward-model#22]

**Comment by pvjosue** [comment]
Committed here: https://github.com/PolarizedLightFieldMicroscopy/forward-model/commit/248df7df2e59d8062c7c8809ed94a8bcfcebb18c

Ready, to plot the lines and volume use:
`
# Plot the volume
plotly_figure = my_volume.plot_lines_plotly()
my_volume.plot_volume_plotly(optical_info, voxels_in=my_volume.get_delta_n(), opacity=0.05, fig=plotly_figure)
`
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/1091910/208253570-97b8a525-6cf8-4869-8f4a-5410ae9e4af5.png">

**Comment by pvjosue** [comment]
Happy to change things according to your recommendations

**Comment by gschlafly** [comment]
Incorporated this method into the streamlit pages!
