### ISSUE TITLE
Volume projections in Reconstruction output

### ISSUE THREAD

**Issue by rudolfoldenbourg** [PolarizedLightFieldMicroscopy/forward-model#28]
The shapes of the object projections shown in the right most image of the Reconstruction output are not consistent with the forward projected light field images shown to the left.

**Comment by gschlafly** [comment]
![image](https://user-images.githubusercontent.com/23206511/208147466-b1113b2f-bb3d-42b8-af48-b21d264fc1ea.png)
Here is an example of the MIP image that is inconsistent with the volume orientation used to generate the retardance image.

**Comment by pvjosue** [comment]
Hi, could you share some commit to replicate this? :)
Or the optical_settings + volume initialization parameters.
Thanks

**Comment by pvjosue** [comment]
Also, what's the inconsistency?

**Comment by gschlafly** [comment]
The example above is for a bundle (I think bundleX.h5) such that the optic axis is parallel with the microscope axis. The retardance and azimuth images look appropriate for this volume. However, the angles projected in the MIP do not seem to correspond with what we would expect. The primary angle of the MIP, which is what I would think should be the axial image, should have a circular shape, while the other two should be rectangles.

**Comment by pvjosue** [comment]
Interesting! Ok, I'll check it out =D, thanks for the details

**Comment by pvjosue** [comment]
The plotting was transposed indeed. You can find a fix in the latest commit: [25a0e68e0b69ba88021d6168e08848e902d093a5](https://github.com/PolarizedLightFieldMicroscopy/forward-model/commit/25a0e68e0b69ba88021d6168e08848e902d093a5)

For clarity, in the MIP:
- The big area shows, the MIP along the axial dimension, so we should expect a rectangle.
- The other two are Y-axial and Z-axial (given that x is the axial dimension).
Here some new images:
- 2D images (sum projections)
<img width="884" alt="image" src="https://user-images.githubusercontent.com/1091910/208267074-d4289cb3-3d15-489f-867e-ef753bea2c10.png">

- The 3D volume:
A view from the microscope point of view:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1091910/208267095-79575e3c-4f64-4ce4-8ae2-e89f4c7703e7.png">
- Perspective views:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/1091910/208267028-d54e31c0-013e-4f76-a4f3-da6c3048b1f8.png">
<img width="390" alt="image" src="https://user-images.githubusercontent.com/1091910/208267043-5e9f9322-6c11-4a5b-bb02-bf8d7d91d7a7.png">
- And a side view:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/1091910/208267053-d9f33af7-e1f0-4fbf-85c0-b2be44ddeebe.png">

**Comment by pvjosue** [comment]
Also the axial projections were scaled by 2, here without scale:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/1091910/208526298-31a05144-4fe3-4a4e-8824-8bcd2ef32d35.png">

**Comment by pvjosue** [comment]
It seems that the bundle(X,Y,XY).h5 etc, have the optic axes stored in flipped order (ZYX instead of XYZ).

If I load the volume as it's stored (bundleXY.h5):
<img width="688" alt="image" src="https://user-images.githubusercontent.com/1091910/208533950-c57da32c-cf7c-4045-9bfc-f717a45e3632.png">

And, If I flip them when loading:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1091910/208534395-8633a3e0-cb75-44b8-9ff8-88e81b47299a.png">

@rudolfoldenbourg could you please check if the h5 generation in Mathematica is storing the volumes correctly?

**Comment by rudolfoldenbourg** [comment]
We seem to have come upon the same issue independently. I just left a note under streamline issues that addresses the same problem. Next, I will upload a bundle file bundleX_B.h5, in which I reverse the indices of the optic axis orientation.

**Comment by gschlafly** [comment]
@rudolfoldenbourg I do not think your ordering of the optic axis dimension indices is the issue. Josue and I just discussed this issue. He thinks they might be being transposed when they are being read in python.

@pvjosue I ran into a dimensions issue when trying use the bundleX_B.h5 file. The plotting and Jones matrix calculations were not able to be performed. Below is the error output for the plotting step.
![image](https://user-images.githubusercontent.com/23206511/208538089-2bdcd3a0-9efd-4e68-b43f-563d3284f050.png)

**Comment by rudolfoldenbourg** [comment]
Please disregard my previous bundleX_B.h5 file, which I deleted in the meanwhile. The bundleX_C.h5 file now holds the arrays, in which I reversed the indices of the optic axis orientation, but not the array indices. Please try this file.

**Comment by gschlafly** [comment]
@rudolfoldenbourg I received the same error message as I did for the bundleX_B.h5 file when I used the new bundleX_C.h5.

**Comment by gschlafly** [comment]
https://github.com/PolarizedLightFieldMicroscopy/forward-model/issues/28#issuecomment-1358471297
@pvjosue The "flipped" version when loaded looks more accurate. I say that based on the image...not know what exactly is being flipped.

**Comment by rudolfoldenbourg** [comment]
There is still an inconsistency when I produce the other bundle objects (bundleY and bundleZ) using the same process of reversing the optic_axis indices. I am wondering why bundleX_D.h5 produces an error message when calculating the retardance and azimuth images. Rendering its volume looks fine.
I'm done for the day, I'll respond again tomorrow.

**Comment by rudolfoldenbourg** [comment]
This keeps me up at night: To make the indices of the delta_n array and of the optic_axis array more consistent with each other, it would help to have the first three indices of the optic_axis identify a voxel, like it does for the delta_n array, and the fourth index identify the three vector components of the optic axis at that voxel. Do you think you can modify your code to reflect this index order?
We also should agree on which of the first three index positions correspond to the microscope axis, and which to call the X-, Y-, and Z-direction.

**Comment by pvjosue** [comment]
Sorry for the late response, I was traveling for the past two days :)
Rudolf, version E seems good.
<img width="574" alt="image" src="https://user-images.githubusercontent.com/1091910/209047934-17a9c6d8-0343-4f21-982e-1bf50d10d8b4.png">

And to answer your last question, seems like we are storing the optic axis as:
[3, axial_dimension, Y, X]
But we can change it to whatever version works well. Even changing the 3 components to the end of the tensor:
[axial_diemsion, Y, X, 3]
As you wish :)

**Comment by rudolfoldenbourg** [comment]
If the index order [3, axial_diemension, Y, X] is better for PyTorch processing, then I agree to keep it that way.

The 3 at the beginning represent the 3 indices of the optic axis vector components. The vector components are given in the same coordinate system as the array. Hence, is the expected sequence of vector components the same as for the whole array, such as [Z, Y, X], or is the sequence inverted, such as [X, Y, Z]?

**Comment by pvjosue** [comment]
Yes, the 3 axis components order should be the same as the data :)

**Comment by rudolfoldenbourg** [comment]
Over Christmas, Saint Nick (SN) has dropped four new HDF5 files in the stream branch:  
![bundles_SN](https://user-images.githubusercontent.com/2894530/209754628-50167932-572a-4c6d-a23a-2ca062f29591.jpeg)
In each bundle object, the delta_n data (birefringence) are given as a 3D array delta_n[Z,Y,X] with indices identifying voxels along the Z-, Y-, and X-axis.  
The optic_axis data are given as a four dimensional array optic_axis[oa,Z,Y,X] with oa representing the optic axis as a 3D unit vector for each voxel [Z,Y,X]. The order of the vector components is [oaZ,oaY,oaX].
I hope this resolves the issue.

**Comment by rudolfoldenbourg** [comment]
I deleted the old bundle files

**Comment by gschlafly** [comment]
Great gift from Saint Nick!
