### ISSUE TITLE
Add mathematica file used to generate h5 volumes

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/forward-model#29]
It would be great if the section of mathematica code used to generate the birefringent objects was extracted into its own file. It can be uploaded to the objects folder of this repository.

**Comment by rudolfoldenbourg** [comment]
will do

**Comment by rudolfoldenbourg** [comment]
I uploaded the Notebook BirefrObjectGeneratorDec2022.nb to the object directory

**Comment by gschlafly** [comment]
Great! I see it, and I will _close_ this issue now.
