### ISSUE TITLE
Streamlit issues

### ISSUE THREAD

**Issue by rudolfoldenbourg** [PolarizedLightFieldMicroscopy/forward-model#30]
I ran streamline User_Interface.py semi-successfully on my Mac today. I uploaded bundleX.h5 and tried to plot the volume using the "Plot Volume!" underneath, but no volume was plotted. Then I clicked the "Calculate!" button under  the section "Retardance and azimuth images". The calculation completed and below is a screen shot of the complete interface with output:
![SreamlitBundleXRetAzim](https://user-images.githubusercontent.com/2894530/208525711-2f9c42b1-d119-47cd-91af-2551c4700a05.jpg)

While the retardance and orientation image seem to be correct in terms of the microscope axis being parallel to the optic axis of the bundle birefringence, the outline of the bundle seems to show its long axis perpendicular to microscope axis, which is contrary to my expectation. 

There seems to be still a mixup in how the different dimensions of the object and its optic axis vector are represented:

In Mathematica, the dimensions of the arrays in the bundleX.h5 file have the following dimensions:
delta_n array has dimensions [5,5,7], hence the long dimension in the X-direction is the last index. 
optic_axis array has dimensions [3,5,5,7]. The first index, which is 3, refers to the 3 indices of the optic-axis vector. The three indices refer to the x-, y-, and z-component of the optic axis, which is [-1,0,0] for bundleX. Hence, there is a flip in the sequence of indices referring to the x-, y-, and z-directions between the array indices and the vector indices.

Do you account for this flip?  Or shall I reorder the arrays in the h5 files?

**Comment by gschlafly** [comment]
@rudolfoldenbourg It seems that the version of the code that you are running is not the most updated version. Regardless, this does not answer your flipping dimensions question. You can do the following to use the most updated version:

1. Select "Fetch orign" followed by "Pull origin" at the top of GitHub Desktop in either the "main" or "stream" branch of the "forward-model" repository.
2. In the terminal in the directory "forward-model", enter `streamlit run User_Interface.py`.

**Comment by rudolfoldenbourg** [comment]
Thank you, Geneva, I have updated both, the stream and main branch. In the main branch, there are still changes listed in my Github Desktop, which I don't know what to do with. I am attaching a screen shot of the Github Desktop window:
<img width="1072" alt="Screenshot 2022-12-20 at 5 28 52 PM" src="https://user-images.githubusercontent.com/2894530/208779804-068dd829-23ae-46b7-abaa-b01d3149a289.png">
Can you recommend what to do with these 5 Changes?

**Comment by gschlafly** [comment]
Haha yes it is annoying how those .pyc files are listed in the _changed files list_. They are created by the python scripts as a way to stored cached (temporary) information. For all practical purposes, they can be ignored. **To more easily ignore them, I uploaded a .gitignore file that will have git ignore all files ending in .pyc.** This means that the files will still exist as normal on your computer, but git will not try to track them.

**So, if you now select "Fetch origin" followed by "Pull origin", they should disappear from the _changed files list_.**

**Comment by rudolfoldenbourg** [comment]
Thanks for explaining the origin of these files. They disappeared from the list after I switched from the main branch to stream and back to main, and clicked the Discard button when asked if I want to reinstate the changes.

**Comment by gschlafly** [comment]
Saint Nick brought new objects with the dimensions flipped.
