### ISSUE TITLE
Ray voxel indices not within volume

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/forward-model#31]
#### Description
Forward model within reconstruction script is not working for many of the object types. See the traceback error message in the screenshot below. This might relate to the same error message described in https://github.com/PolarizedLightFieldMicroscopy/forward-model/issues/28#issuecomment-1358494352.

#### Screenshots
![image](https://user-images.githubusercontent.com/23206511/208755438-be219a57-4ead-4265-9535-abb6160e0f03.png)

#### Files
- main_3d_reconstruction_12_20.py
- VolumeRaytraceLFM\birefringence_implementations.py
- objects\ellipsoid_12_20.h5

#### To Reproduce
Run the script main_3d_reconstruction_12_20.py. Use either `volume_type = 'ellipsoid'`, or the saved volume objects/ellipsoid_12_20.h5.

#### Solution Ideas
- [ ] Compare reconstruction script to the forward model script which seems to apply the forward model of the same volume without any issue.
- [ ] Plot a ray passing through the volume.
- [ ] Check if some padding is occurring because the indices are only slightly out of range.
- [ ] Examine issue with `volume_type = 'single_voxel'`, which does not raise an error, but also does not reconstruct the single voxel.

**Comment by pvjosue** [comment]
Something broke after this commit:
https://github.com/PolarizedLightFieldMicroscopy/forward-model/commit/7ae9d1fd0a60add9c8707ee995e482467ed41144

**Comment by pvjosue** [comment]
By changing the refractive index of the medium here:
https://github.com/PolarizedLightFieldMicroscopy/forward-model/blob/27b5ef9c179bf49841fc887e59970b8cbcf58ff8/VolumeRaytraceLFM/abstract_classes.py#L60
The rays span go beyond the volume area.

This assert is not triggering correctly:
https://github.com/PolarizedLightFieldMicroscopy/forward-model/blob/27b5ef9c179bf49841fc887e59970b8cbcf58ff8/VolumeRaytraceLFM/birefringence_implementations.py#L605

Which means that this variable is not being computed correctly:
https://github.com/PolarizedLightFieldMicroscopy/forward-model/blob/27b5ef9c179bf49841fc887e59970b8cbcf58ff8/VolumeRaytraceLFM/abstract_classes.py#L459

So, a quick fix, is to increase the volume shape to [11,31,31] in the main_3d_reconstruction.py

Will look for a correct solution though.

**Comment by pvjosue** [comment]
Possible fix by calculating the maximum volume reach of the rays using the rays direction.
In commit: https://github.com/PolarizedLightFieldMicroscopy/forward-model/commit/c6684901ec735cc5e97474dce91173e92740a2aa

**Comment by gschlafly** [comment]
Interesting
