### ISSUE TITLE
Dimension of ground truth vs predicted volume

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/forward-model#46]
#### Description
The dimensions of the ground truth MIP images appear to be about 5x that of the predicted volume, even when using the same supersampling when sampling the volume and in volume space when creating the volume. @pvjosue do you know why this is happening?

I believe the axes are both in voxel units, so I would expect the dimensions to the same given the same supersampling.

#### Example supersample combinations
reconstruction volume sampling: 1, creating volume: 1
<img width="1237" alt="single_voxel_mla9_samplingo1v1" src="https://github.com/PolarizedLightFieldMicroscopy/forward-model/assets/23206511/063cee75-a308-4048-9ff9-dc1a0b081b1e">
reconstruction volume sampling: 3, creating volume: 3
<img width="1465" alt="single_voxel_mla9_samplingo3v3" src="https://github.com/PolarizedLightFieldMicroscopy/forward-model/assets/23206511/7b4c2949-888b-453c-9894-cf04b67fd4ac">
reconstruction volume sampling: 1, creating volume: 3
![single_voxel_mla9_samplingo1v3](https://github.com/PolarizedLightFieldMicroscopy/forward-model/assets/23206511/9c72314a-a3ed-4f5d-96b2-3e6831c19522)
reconstruction volume sampling: 3, creating volume: 1
![single_voxel_mla9_samplingo3v1](https://github.com/PolarizedLightFieldMicroscopy/forward-model/assets/23206511/966062a8-2bdf-443a-8136-44945538285d)

#### To Reproduce
<img width="561" alt="single_voxel_mla9_samplingo1v1_parameters" src="https://github.com/PolarizedLightFieldMicroscopy/forward-model/assets/23206511/b9ce9bf8-c2e8-4611-997a-4a931df42799">

**Comment by pvjosue** [comment]
Yeah, I think I found it, and it's my fault (lol). I hardcoded the GT volume size to be large and avoid problems with the micro-lenses when doing a forward projection. I set it to 501 here https://github.com/PolarizedLightFieldMicroscopy/forward-model/blob/a69ab8c35243ccb2d7438443f393e51507e858cc/pages/2_Reconstruction.py#L214

Now removed on the next commit.

**Comment by pvjosue** [comment]
I did this as for the case when we want to simulate the images from a GT volume with higher sampling as the reconstruction. I set it to 501 just to have something large there. This might interfere with you fix for the relationship between number of microlenses and volume shape. 
You'll notice that without this hardcoded value it often fails when generating the forward projection.
